package com.homebrain.agent.domain

/**
 * Initial request from the user to generate automation code.
 */
data class CodeGenerationRequest(
    val userMessage: String,
    val existingAutomationId: String? = null
)

/**
 * Context gathered for code generation, including available MQTT topics
 * and any existing automation code to modify.
 */
data class CodeGenerationContext(
    val userMessage: String,
    val availableTopics: List<String>,
    val existingCode: String? = null,
    val existingAutomationId: String? = null
)

/**
 * Prompts constructed for the LLM, ready to be sent.
 */
data class CodeGenerationPrompt(
    val systemPrompt: String,
    val userPrompt: String,
    val existingAutomationId: String? = null
)

/**
 * Raw code generated by the LLM before cleaning.
 */
data class GeneratedCodeRaw(
    val rawCode: String,
    val userMessage: String,
    val existingAutomationId: String? = null
)

/**
 * Final goal state: cleaned, deployment-ready automation code.
 */
data class GeneratedAutomationCode(
    val code: String,
    val filename: String,
    val explanation: String? = null
)
